[package]
name = "watermarker"
version = "0.3.0"
edition = "2021"
authors = ["xomvio <xomvio at proton dot me>"]
description = "Watermarker is a CLI tool for adding watermark to images."
repository = "https://github.com/xomvio/watermarker"
license = "GPL-3.0-or-later"


[dependencies]
tokio = { version = "1.50.0", features = ["rt", "rt-multi-thread", "macros", "fs"] }
image = "0.25.10"
clap = { version = "4.6.0", features = ["derive"] }
anyhow = "1.0.102"